import { DatabaseDialect } from '../types/enums';

// Cross-dialect data type mapping for migration
export const DATA_TYPE_MAP: Record<string, Partial<Record<DatabaseDialect, string>>> = {
  // Integer types
  'SMALLINT': {
    [DatabaseDialect.POSTGRESQL]: 'SMALLINT',
    [DatabaseDialect.MYSQL]: 'SMALLINT',
    [DatabaseDialect.ORACLE]: 'NUMBER(5)',
    [DatabaseDialect.SQLSERVER]: 'SMALLINT',
    [DatabaseDialect.SNOWFLAKE]: 'SMALLINT',
    [DatabaseDialect.BIGQUERY]: 'INT64',
  },
  'INTEGER': {
    [DatabaseDialect.POSTGRESQL]: 'INTEGER',
    [DatabaseDialect.MYSQL]: 'INT',
    [DatabaseDialect.ORACLE]: 'NUMBER(10)',
    [DatabaseDialect.SQLSERVER]: 'INT',
    [DatabaseDialect.SNOWFLAKE]: 'INTEGER',
    [DatabaseDialect.BIGQUERY]: 'INT64',
  },
  'BIGINT': {
    [DatabaseDialect.POSTGRESQL]: 'BIGINT',
    [DatabaseDialect.MYSQL]: 'BIGINT',
    [DatabaseDialect.ORACLE]: 'NUMBER(19)',
    [DatabaseDialect.SQLSERVER]: 'BIGINT',
    [DatabaseDialect.SNOWFLAKE]: 'BIGINT',
    [DatabaseDialect.BIGQUERY]: 'INT64',
  },
  'SERIAL': {
    [DatabaseDialect.POSTGRESQL]: 'SERIAL',
    [DatabaseDialect.MYSQL]: 'INT AUTO_INCREMENT',
    [DatabaseDialect.ORACLE]: 'NUMBER GENERATED BY DEFAULT AS IDENTITY',
    [DatabaseDialect.SQLSERVER]: 'INT IDENTITY(1,1)',
    [DatabaseDialect.SNOWFLAKE]: 'INT AUTOINCREMENT',
    [DatabaseDialect.BIGQUERY]: 'INT64',
  },
  // Text types
  'VARCHAR': {
    [DatabaseDialect.POSTGRESQL]: 'VARCHAR',
    [DatabaseDialect.MYSQL]: 'VARCHAR',
    [DatabaseDialect.ORACLE]: 'VARCHAR2',
    [DatabaseDialect.SQLSERVER]: 'NVARCHAR',
    [DatabaseDialect.SNOWFLAKE]: 'VARCHAR',
    [DatabaseDialect.BIGQUERY]: 'STRING',
  },
  'TEXT': {
    [DatabaseDialect.POSTGRESQL]: 'TEXT',
    [DatabaseDialect.MYSQL]: 'LONGTEXT',
    [DatabaseDialect.ORACLE]: 'CLOB',
    [DatabaseDialect.SQLSERVER]: 'NVARCHAR(MAX)',
    [DatabaseDialect.SNOWFLAKE]: 'VARCHAR(16777216)',
    [DatabaseDialect.BIGQUERY]: 'STRING',
  },
  // Date/Time types
  'TIMESTAMP': {
    [DatabaseDialect.POSTGRESQL]: 'TIMESTAMP',
    [DatabaseDialect.MYSQL]: 'DATETIME',
    [DatabaseDialect.ORACLE]: 'TIMESTAMP',
    [DatabaseDialect.SQLSERVER]: 'DATETIME2',
    [DatabaseDialect.SNOWFLAKE]: 'TIMESTAMP_NTZ',
    [DatabaseDialect.BIGQUERY]: 'TIMESTAMP',
  },
  'DATE': {
    [DatabaseDialect.POSTGRESQL]: 'DATE',
    [DatabaseDialect.MYSQL]: 'DATE',
    [DatabaseDialect.ORACLE]: 'DATE',
    [DatabaseDialect.SQLSERVER]: 'DATE',
    [DatabaseDialect.SNOWFLAKE]: 'DATE',
    [DatabaseDialect.BIGQUERY]: 'DATE',
  },
  // Numeric types
  'DECIMAL': {
    [DatabaseDialect.POSTGRESQL]: 'DECIMAL',
    [DatabaseDialect.MYSQL]: 'DECIMAL',
    [DatabaseDialect.ORACLE]: 'NUMBER',
    [DatabaseDialect.SQLSERVER]: 'DECIMAL',
    [DatabaseDialect.SNOWFLAKE]: 'DECIMAL',
    [DatabaseDialect.BIGQUERY]: 'NUMERIC',
  },
  'BOOLEAN': {
    [DatabaseDialect.POSTGRESQL]: 'BOOLEAN',
    [DatabaseDialect.MYSQL]: 'TINYINT(1)',
    [DatabaseDialect.ORACLE]: 'NUMBER(1)',
    [DatabaseDialect.SQLSERVER]: 'BIT',
    [DatabaseDialect.SNOWFLAKE]: 'BOOLEAN',
    [DatabaseDialect.BIGQUERY]: 'BOOL',
  },
  // Binary types
  'BYTEA': {
    [DatabaseDialect.POSTGRESQL]: 'BYTEA',
    [DatabaseDialect.MYSQL]: 'LONGBLOB',
    [DatabaseDialect.ORACLE]: 'BLOB',
    [DatabaseDialect.SQLSERVER]: 'VARBINARY(MAX)',
    [DatabaseDialect.SNOWFLAKE]: 'BINARY',
    [DatabaseDialect.BIGQUERY]: 'BYTES',
  },
  // JSON types
  'JSON': {
    [DatabaseDialect.POSTGRESQL]: 'JSONB',
    [DatabaseDialect.MYSQL]: 'JSON',
    [DatabaseDialect.ORACLE]: 'CLOB',
    [DatabaseDialect.SQLSERVER]: 'NVARCHAR(MAX)',
    [DatabaseDialect.SNOWFLAKE]: 'VARIANT',
    [DatabaseDialect.BIGQUERY]: 'JSON',
  },
  // UUID types
  'UUID': {
    [DatabaseDialect.POSTGRESQL]: 'UUID',
    [DatabaseDialect.MYSQL]: 'CHAR(36)',
    [DatabaseDialect.ORACLE]: 'RAW(16)',
    [DatabaseDialect.SQLSERVER]: 'UNIQUEIDENTIFIER',
    [DatabaseDialect.SNOWFLAKE]: 'VARCHAR(36)',
    [DatabaseDialect.BIGQUERY]: 'STRING',
  },
};
